/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GraphicInterface;

import DataStructures.Grafo;
import javax.swing.JOptionPane;

/**
 * Esta interfaz tiene la función de agregar arcos dentro del grafo
 * @authors Georgina Akel, Orveo Di Luca, Juan Nunes, Arianne Perret Gentil
 * @version 03/06/2023
 */
public class InputEdge extends javax.swing.JFrame {
    private int start;
    private int end;
    private int weight;
    private static Grafo graph;
    private static String fileRoute;
    private boolean run;
    
    /**
     * Crea la interfaz
     * @param graph
     * @param fileRoute
     */
    public InputEdge(Grafo graph, String fileRoute) {
        initComponents();
        this.graph = graph;
        this.fileRoute = fileRoute;
        setLocationRelativeTo(null);
        this.run = false;
    }
    
    /**
     * Agrega una relacion en el grafo
     */
    public void addRelation(){
        try{      
            String startStr = startInput.getText();
            if(startStr.contains("@")){
                startStr = startStr.replace("@", "");
            }
            
            String endStr = endInput.getText();
            if(endStr.contains("@")){
                endStr = endStr.replace("@", "");
            }
            
            startStr = "@" + startStr;
            endStr = "@" + endStr;
            
            start = graph.nameToVnum(startStr);
            end = graph.nameToVnum(endStr);
            weight = Integer.parseInt(weightInput.getText());

            graph.addEdge(start, end, weight);       
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Error: dato ingresado no valido");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        startInput = new javax.swing.JTextField();
        endInput = new javax.swing.JTextField();
        weightInput = new javax.swing.JTextField();
        finish = new javax.swing.JButton();
        back = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 6, -1, -1));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Ingrese el primer usuario");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 204));
        jLabel2.setText("Ingrese el segundo usuario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Ingrese los años de relacion ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        startInput.setBackground(new java.awt.Color(255, 204, 0));
        startInput.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        startInput.setForeground(new java.awt.Color(0, 0, 204));
        startInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startInputActionPerformed(evt);
            }
        });
        getContentPane().add(startInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 258, -1));

        endInput.setBackground(new java.awt.Color(255, 204, 0));
        endInput.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        endInput.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(endInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 258, -1));

        weightInput.setBackground(new java.awt.Color(255, 204, 0));
        weightInput.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        weightInput.setForeground(new java.awt.Color(0, 0, 204));
        weightInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightInputActionPerformed(evt);
            }
        });
        getContentPane().add(weightInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 420, 258, -1));

        finish.setBackground(new java.awt.Color(255, 204, 0));
        finish.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        finish.setForeground(new java.awt.Color(0, 0, 204));
        finish.setText("Continuar");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        getContentPane().add(finish, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 110, 40));

        back.setBackground(new java.awt.Color(255, 204, 0));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Regresar.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 590, 60, -1));

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("Para agregar una relación ambos usarios deben de existir,");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("si deseas crear un nuevo usuario puedes hacerlo en \"Agregar persona\"");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void weightInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightInputActionPerformed

    private void startInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startInputActionPerformed
    /**
     * Conduce a la interfaz de InterfaceMain despues de crear una relacion
     * @param evt 
     */
    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        addRelation();
        InterfaceMain in1 = new InterfaceMain(graph, fileRoute);
        this.dispose();
        in1.setVisible(true);
    }//GEN-LAST:event_finishActionPerformed
    /**
     * Conduce a la interfaz de InterfaceMain 
     * @param evt 
     */
    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.dispose();
        InterfaceMain inter2 = new InterfaceMain(graph, fileRoute);
        inter2.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputEdge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputEdge(graph, fileRoute).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton back;
    private javax.swing.JTextField endInput;
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField startInput;
    private javax.swing.JTextField weightInput;
    // End of variables declaration//GEN-END:variables
}
