/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GraphicInterface;

import DataStructures.Grafo;

/**
 * Esta interfaz es la encargada de mostrar la cantidad de islas utilizando los recorridos BFS y DFS
 * @authors Georgina Akel, Orveo Di Luca, Juan Nunes, Arianne Perret Gentil
 * @version 03/06/2023
 */
public class ShowBfs_Dfs extends javax.swing.JFrame {
    private static Grafo graph;
    private static String fileRoute;

    /**
     * Crea la Interfaz
     */
    public ShowBfs_Dfs(Grafo graph, String fileRoute) {
        this.graph = graph;
        this.fileRoute = fileRoute;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaBFS = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaDFS = new javax.swing.JTextArea();
        bfs = new javax.swing.JButton();
        DFS = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        textAreaBFS.setBackground(new java.awt.Color(255, 204, 0));
        textAreaBFS.setColumns(20);
        textAreaBFS.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        textAreaBFS.setForeground(new java.awt.Color(0, 0, 204));
        textAreaBFS.setRows(5);
        jScrollPane1.setViewportView(textAreaBFS);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 300, 140));

        textAreaDFS.setBackground(new java.awt.Color(255, 204, 0));
        textAreaDFS.setColumns(20);
        textAreaDFS.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        textAreaDFS.setForeground(new java.awt.Color(0, 0, 204));
        textAreaDFS.setRows(5);
        jScrollPane2.setViewportView(textAreaDFS);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 300, 130));

        bfs.setBackground(new java.awt.Color(255, 204, 0));
        bfs.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        bfs.setForeground(new java.awt.Color(0, 0, 204));
        bfs.setText("BFS");
        bfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsActionPerformed(evt);
            }
        });
        getContentPane().add(bfs, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 100, 40));

        DFS.setBackground(new java.awt.Color(255, 204, 0));
        DFS.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        DFS.setForeground(new java.awt.Color(0, 0, 204));
        DFS.setText("DFS");
        DFS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DFSActionPerformed(evt);
            }
        });
        getContentPane().add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 90, 40));

        Back.setBackground(new java.awt.Color(255, 204, 0));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Regresar.png"))); // NOI18N
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 600, 60, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Muestra la cantidad de islas utilizando el recorrido bfs
     * @param evt 
     */
    private void bfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsActionPerformed
        graph.clearVisited();
        int islandsNum = graph.countIslandsBFS();
        textAreaBFS.setText("El numero de islas es de: " + islandsNum);
    }//GEN-LAST:event_bfsActionPerformed
    private void DFSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DFSActionPerformed
        graph.clearVisited();
        int islandsNum = graph.countIslandsDFS();
        textAreaDFS.setText("El numero de islas es de: " + islandsNum);      
    }//GEN-LAST:event_DFSActionPerformed
    /**
     * Conduce a la interfaz principal
     * @param evt 
     */
    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        InterfaceMain in1 = new InterfaceMain(graph, fileRoute);
        in1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowBfs_Dfs(graph, fileRoute).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JButton DFS;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton bfs;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea textAreaBFS;
    private javax.swing.JTextArea textAreaDFS;
    // End of variables declaration//GEN-END:variables
}
